class_name ProjectFiles

class Scripts:
	const BACKGROUND_THEME = "res://scenes/BackGroundScene/background_theme.gd"
	const CARD = "res://scenes/CardScene/scripts/card.gd"
	const CARD_BUFFER = "res://scenes/CardScene/scripts/card_buffer.gd"
	const CARD_MANAGER = "res://scenes/CardScene/scripts/card_manager.gd"
	const CONNECTION_MANAGER = "res://scenes/Multiplayer/connection_manager.gd"
	const CONSTANTS = "res://scenes/scripts/constants.gd"
	const DRAG_STATE = "res://scenes/scripts/drag_state.gd"
	const MAIN_MENU_OPTIONS = "res://scenes/MainMenuScene/main_menu_options.gd"
	const MULTIPLAYER_CARD_MANAGER = "res://scenes/Multiplayer/MultiplayerGame/multiplayer_card_manager.gd"
	const MULTIPLAYER_LOBBY = "res://scenes/Multiplayer/Lobby/multiplayer_lobby.gd"
	const MULTIPLAYER_OPTIONS = "res://scenes/MainMenuScene/Multiplayer/multiplayer_options.gd"
	const OPTIONS_DIALOG_SCRIPT = "res://scenes/MainMenuScene/Options/options_dialog_script.gd"
	const PLAYER_IN_LOBBY = "res://scenes/Multiplayer/Lobby/player_in_lobby.gd"
	const SCENE_MANAGER = "res://scene_manager.gd"
	const SCROLL_CONTAINER = "res://scenes/scroll_container.gd"
	const SETTINGS = "res://settings.gd"
	const SINGLEPLAYER_OPTIONS = "res://scenes/MainMenuScene/Singleplayer/singleplayer_options.gd"
	const SUBARRAY_UTILS = "res://res/algorithms/SubarrayUtils.gd"
	const SWAP_BTN = "res://scenes/CardScene/scripts/swap_btn.gd"
	const THEME_AUTOAPPLIER = "res://scenes/scripts/theme_autoapplier.gd"
	const THEME_MANAGER = "res://theme_manager.gd"
	const TIMER_CONTROLLER_SCRIPT = "res://scenes/timer_controller_script.gd"

class Scenes:
	const BACKGROUND = "res://scenes/BackGroundScene/background.tscn"
	const CARD_MAIN = "res://scenes/CardScene/CardMain.tscn"
	const CARD_SLOT = "res://scenes/CardScene/CardSlot.tscn"
	const DROP_INDICATOR = "res://scenes/CardScene/DropIndicator.tscn"
	const FINISH_GAME_SCENE = "res://scenes/CardScene/FinishGameScene.tscn"
	const GAME_OPTIONS = "res://scenes/MainMenuScene/Options/game_options.tscn"
	const MENU_SCENE = "res://scenes/MainMenuScene/menu_scene.tscn"
	const MULTIPLAYER_GAME_SCENE = "res://scenes/Multiplayer/MultiplayerGame/multiplayer_game_scene.tscn"
	const MULTIPLAYER_LOBBY_SCENE = "res://scenes/Multiplayer/Lobby/multiplayer_lobby_scene.tscn"
	const MULTIPLAYER_OPTIONS = "res://scenes/MainMenuScene/Multiplayer/multiplayer_options.tscn"
	const PLAYER_IN_LOBBY_SCENE = "res://scenes/Multiplayer/Lobby/player_in_lobby_scene.tscn"
	const SINGLEPLAYER_OPTIONS = "res://scenes/MainMenuScene/Singleplayer/singleplayer_options.tscn"
	const SINGLEPLAYER_SCENE = "res://scenes/Singleplayer/singleplayer_scene.tscn"
	const SWAP_BTN = "res://scenes/CardScene/swapBtn.tscn"

class Resources:
	const BACKGROUND_STYLEBLOX = "res://res/background_styleblox.tres"
	const DARK_THEME = "res://res/dark_theme.tres"
	const MENU_THEME = "res://res/menu_theme.tres"
	const PLAY_SVG_802978C_6F_452_DDE_0C_40917B_7989F_9A_2D = "res://.godot/imported/play.svg-802978c6f452dde0c40917b7989f9a2d.res"

class Images:
	const GD_SYNC_PROTECTED = "res://GDSync-protected.png"
	const ICON = "res://icon.png"
	const THEME_COLORS = "res://res/theme-colors.jpg"
	const VAR_TREE_PREVIEW = "res://var_tree_preview.png"
	const WEB_EXPORT_144X_144 = "res://exports/web-export/web-export.144x144.png"
	const WEB_EXPORT_180X_180 = "res://exports/web-export/web-export.180x180.png"
	const WEB_EXPORT_512X_512 = "res://exports/web-export/web-export.512x512.png"
	const WEB_EXPORT_APPLE_TOUCH_ICON = "res://exports/web-export/web-export.apple-touch-icon.png"
	const WEB_EXPORT_ICON = "res://exports/web-export/web-export.icon.png"
	const WEB_EXPORT = "res://exports/web-export/web-export.png"

class Fonts:
	const FONT_AWESOME_6_BRANDS_REGULAR_400 = "res://res/fontawesome-free-6.7.2-desktop/otfs/Font Awesome 6 Brands-Regular-400.otf"
	const FONT_AWESOME_6_FREE_REGULAR_400 = "res://res/fontawesome-free-6.7.2-desktop/otfs/Font Awesome 6 Free-Regular-400.otf"
	const FONT_AWESOME_6_FREE_SOLID_900 = "res://res/fontawesome-free-6.7.2-desktop/otfs/Font Awesome 6 Free-Solid-900.otf"
