class_name ProjectFiles

class Scripts:
	const BACKGROUND_THEME = "res://scenes/BackGroundScene/background_theme.gd"
	const CARD = "res://scenes/CardScene/scripts/card.gd"
	const CARD_BUFFER = "res://scenes/CardScene/scripts/card_buffer.gd"
	const CARD_MANAGER = "res://scenes/CardScene/scripts/card_manager.gd"
	const CONSTANTS = "res://scenes/scripts/constants.gd"
	const CREATE_ACCOUNT = "res://GD-SyncTemplates/Accounts/create_account.gd"
	const DRAG_STATE = "res://scenes/scripts/drag_state.gd"
	const LEADERBOARD_BROWSER = "res://GD-SyncTemplates/Leaderboards/leaderboard_browser.gd"
	const LEADERBOARD_LABEL = "res://GD-SyncTemplates/Leaderboards/leaderboard_label.gd"
	const LOBBY_BROWSER = "res://GD-SyncTemplates/LobbyBrowser/lobby_browser.gd"
	const LOBBY_LABEL = "res://GD-SyncTemplates/LobbyBrowser/lobby_label.gd"
	const LOGIN = "res://GD-SyncTemplates/Accounts/login.gd"
	const MAIN_MENU_OPTIONS = "res://scenes/MainMenuScene/main_menu_options.gd"
	const MULTIPLAYER_OPTIONS = "res://scenes/MainMenuScene/Multiplayer/multiplayer_options.gd"
	const OPTIONS_DIALOG_SCRIPT = "res://scenes/MainMenuScene/Options/options_dialog_script.gd"
	const PLAYER = "res://testing/player.gd"
	const SCENE_MANAGER = "res://scene_manager.gd"
	const SCROLL_CONTAINER = "res://scenes/scroll_container.gd"
	const SETTINGS = "res://settings.gd"
	const SINGLEPLAYER_OPTIONS = "res://scenes/MainMenuScene/Singleplayer/singleplayer_options.gd"
	const SUBARRAY_UTILS = "res://res/algorithms/SubarrayUtils.gd"
	const SWAP_BTN = "res://scenes/CardScene/scripts/swap_btn.gd"
	const TEST_SCENE = "res://testing/test_scene.gd"
	const TEXT_CHAT = "res://GD-SyncTemplates/TextChat/text_chat.gd"
	const THEME_AUTOAPPLIER = "res://scenes/scripts/theme_autoapplier.gd"
	const THEME_MANAGER = "res://theme_manager.gd"
	const TIMER_CONTROLLER_SCRIPT = "res://scenes/timer_controller_script.gd"

class Scenes:
	const BACKGROUND = "res://scenes/BackGroundScene/background.tscn"
	const CARD_MAIN = "res://scenes/CardScene/CardMain.tscn"
	const CARD_SLOT = "res://scenes/CardScene/CardSlot.tscn"
	const CREATE_ACCOUNT = "res://GD-SyncTemplates/Accounts/create_account.tscn"
	const DROP_INDICATOR = "res://scenes/CardScene/DropIndicator.tscn"
	const EXPORT_11_CB_3D_0_DA_2470A_82C_44B_8E_5267F_51C_10_CARD_MAIN = "res://.godot/exported/133200997/export-11cb3d0da2470a82c44b8e5267f51c10-CardMain.scn"
	const EXPORT_145F_9_DB_6D_5F_9570F_387680_FF_6D_041953_CARD_SLOT = "res://.godot/exported/133200997/export-145f9db6d5f9570f387680ff6d041953-CardSlot.scn"
	const EXPORT_23A_6E_166365891D_78_EBA_59115_DEF_1384_SINGLEPLAYER_SCENE = "res://.godot/exported/133200997/export-23a6e166365891d78eba59115def1384-singleplayer-scene.scn"
	const EXPORT_B_4B_38B_9550A_57F_0B_3F_51E_91C_9_BD_987_DF_SWAP_BTN = "res://.godot/exported/133200997/export-b4b38b9550a57f0b3f51e91c9bd987df-swapBtn.scn"
	const EXPORT_E_03331_DA_2475062632B_0_FEA_762D_9231C_MENU_SCENE = "res://.godot/exported/133200997/export-e03331da2475062632b0fea762d9231c-menu-scene.scn"
	const GAME_OPTIONS = "res://scenes/MainMenuScene/Options/game_options.tscn"
	const LEADERBOARD_BROWSER = "res://GD-SyncTemplates/Leaderboards/leaderboard_browser.tscn"
	const LEADERBOARD_LABEL = "res://GD-SyncTemplates/Leaderboards/leaderboard_label.tscn"
	const LOBBY_BROWSER = "res://GD-SyncTemplates/LobbyBrowser/lobby_browser.tscn"
	const LOBBY_LABEL = "res://GD-SyncTemplates/LobbyBrowser/lobby_label.tscn"
	const LOGIN = "res://GD-SyncTemplates/Accounts/login.tscn"
	const MENU_SCENE = "res://scenes/MainMenuScene/menu_scene.tscn"
	const MULTIPLAYER_OPTIONS = "res://scenes/MainMenuScene/Multiplayer/multiplayer_options.tscn"
	const MULTIPLAYER_SCENE = "res://scenes/Multiplayer/multiplayer_scene.tscn"
	const SINGLEPLAYER_OPTIONS = "res://scenes/MainMenuScene/Singleplayer/singleplayer_options.tscn"
	const SINGLEPLAYER_SCENE = "res://scenes/singleplayer_scene.tscn"
	const SWAP_BTN = "res://scenes/CardScene/swapBtn.tscn"
	const TEST_SCENE = "res://testing/test_scene.tscn"
	const TEXT_CHAT = "res://GD-SyncTemplates/TextChat/text_chat.tscn"

class Resources:
	const BACKGROUND_STYLEBLOX = "res://res/background_styleblox.tres"
	const DARK_THEME = "res://res/dark_theme.tres"
	const EXPORT_2D_6_DBF_99_BF_124F_62E_2308646F_820_AEEA_NEW_THEME = "res://.godot/exported/133200997/export-2d6dbf99bf124f62e2308646f820aeea-new_theme.res"
	const MENU_THEME = "res://res/menu_theme.tres"

class Images:
	const ICON = "res://icon.png"
	const THEME_COLORS = "res://res/theme-colors.jpg"
	const VAR_TREE_PREVIEW = "res://var_tree_preview.png"
	const WEB_EXPORT_144X_144 = "res://exports/web-export/web-export.144x144.png"
	const WEB_EXPORT_180X_180 = "res://exports/web-export/web-export.180x180.png"
	const WEB_EXPORT_512X_512 = "res://exports/web-export/web-export.512x512.png"
	const WEB_EXPORT_APPLE_TOUCH_ICON = "res://exports/web-export/web-export.apple-touch-icon.png"
	const WEB_EXPORT_ICON = "res://exports/web-export/web-export.icon.png"
	const WEB_EXPORT = "res://exports/web-export/web-export.png"
